services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "${REDIS_HOST_PORT:-6379}:6379"
      - "${REDIS_INSIGHT_PORT:-8001}:8001"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
